# GitLab CI Automation for PantherX Packages
# Author: Franz Geffke <franz@pantherx.org>
# Version: 0.0.4

# Git submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add py-pip
    - pip install --user awscli
    - export PATH="$PATH:/root/.local/bin"
    - export AWS_ACCESS_KEY_ID=$(echo "$AWS_ACCESS_KEY_ID")
    - export AWS_SECRET_ACCESS_KEY=$(echo "$AWS_SECRET_ACCESS_KEY")
    - export AWS_DEFAULT_REGION=eu-central-1
    - tar --exclude='./git' -zcvf $(echo "$CI_PROJECT_NAME")_$(echo "$CI_COMMIT_TAG").tgz .
    - aws s3 cp $(echo "$CI_PROJECT_NAME")_$(echo "$CI_COMMIT_TAG").tgz s3://source-git-pantherx-org/
  only:
    - tags
  tags: [source]
